---
language:     ruby
cache:        bundler
bundler_args: --without metrics
rvm:
  - '1.9.3'
  - '2.0'
  - '2.1'
  - '2.2'
  - ruby-head
  - rbx-2 --1.9
  - rbx-2 --2.1
  - jruby-19mode
  - jruby-20mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
